#!/usr/bin/env python3
"""The codexzig harness exists TWICE. Fail if the two copies' CODE diverges.

    ./check_harness_twin.py [path-to-codex-zig-transpiler]

`ast/CodexZigHarness.codex` here is generated by `gen_codexzig_harness.py`.
`source/CodexZigHarness.codex` in codex-zig-transpiler is hand-maintained, was
committed once at that repo's skeleton commit, and is what `safari-codex` and
`safari-web` actually run. Nothing connected them.

**PROSE IS ALLOWED TO DIFFER AND SHOULD.** Each file explains itself to its own
readers: this one points at `ast/f4_boot.py`, that one at `build.py`'s two
arms. A shared file would have to drop both. What must NOT differ is the code,
because that is the tool's behaviour, and on 2026-08-30 the ladder's copy gained
a diagnostics reporter that the transpiler's did not -- a fix the consumer of
the OTHER copy was the one who needed.

So this compares definition lines only, and says which side has what. It is a
five-second check with no build and no guest; run it after touching either.
"""
import pathlib, subprocess, sys

HERE = pathlib.Path(__file__).resolve().parent
LADDER = HERE / 'ast' / 'CodexZigHarness.codex'


def code_lines(path):
    """Definition lines: prose is any line starting with exactly one space, and
    blank lines carry nothing. Codex marks a definition with two."""
    out = []
    for line in pathlib.Path(path).read_text().splitlines():
        if not line.strip():
            continue
        if line.startswith(' ') and not line.startswith('  '):
            continue                       # one space = prose
        out.append(line.rstrip())
    return out


def main():
    other_root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1
                              else pathlib.Path.home() / 'showell_repos' / 'codex-zig-transpiler')
    twin = other_root / 'source' / 'CodexZigHarness.codex'
    if not LADDER.is_file():
        raise SystemExit(f'no {LADDER} -- run ast/gen_codexzig_harness.py first')
    if not twin.is_file():
        raise SystemExit(f'no {twin} -- pass the transpiler checkout as argv[1]')

    a, b = code_lines(LADDER), code_lines(twin)
    if a == b:
        print(f'harness twins agree: {len(a)} code lines, prose differs by design')
        print(f'  ladder     {LADDER}')
        print(f'  transpiler {twin}')
        return 0

    print(f'HARNESS TWINS DIVERGE: ladder {len(a)} code lines, transpiler {len(b)}')
    import difflib
    for d in difflib.unified_diff(b, a, 'transpiler', 'ladder', lineterm='', n=1):
        print('  ' + d)
    print('\nProse may differ. Code may not -- one of these is what safari runs.')
    return 1


if __name__ == '__main__':
    sys.exit(main())
