& "$PSScriptRoot/ast/bundle_ir_to_x86.ps1" -OutName 'driver-probe.codex' -PlugName 'driver-probe' -ExtraChapters @(
  'codex/foreword/core/Maybe.codex',
  'codex/foreword/core/Wrap64.codex',
  'codex/foreword/core/CCE.codex',
  'codex/foreword/core/Fat16.codex',
  'codex/foreword/core/ImportGate.codex',
  'codex/foreword/core/FactDisk.codex',
  'codex/compiler/Emit/CodexEmitter.codex',
  'codex/compiler/IR/LirTargets.codex',
  'codex/compiler/IR/Occurrence.codex',
  'codex/compiler/IR/IRCheck.codex',
  'codex/compiler/IR/LambdaLifting.codex',
  'codex/compiler/IR/Simplify.codex',
  'codex/compiler/IR/Passes.codex',
  'codex/compiler/opening.codex')
