#!/usr/bin/env python3
"""Generate FibHarness.codex: the front-end chain compiling fib END TO END,
with the compiler's own serialization as output. The lower harness proved
each phase; this one is the deliverable shape -- source text in, one
(def ...) line per definition out, in the exact grammar IRTextEmitter
writes to the IR-CCE wire. The summary counts stay as a preamble so a
diff names the phase that moved before it names the def.

LowerStubs.codex (the bs-emit-stripped Builtins table) is generated by
gen_lower_harness.py; this generator invokes it so the stub can never be
stale when only the fib rung runs."""
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).parent
subprocess.run([sys.executable, str(HERE / 'gen_lower_harness.py')], check=True)

FIB = (
    'Chapter: Fib\n'
    '\n'
    'Section: Math\n'
    '  fib : Integer -> Integer\n'
    '  fib (n) =\n'
    '   if n <= 1 then n\n'
    '   else fib (n - 1) + fib (n - 2)\n'
    '\n'
    '  double : Integer -> Integer\n'
    '  double (n) = n + n\n'
    '\n'
    'Section: Main\n'
    '  opening : [Console] Nothing = act\n'
    '   print-line-uni (show (fib 20))\n'
    '  end\n'
)


def codex_literal(s):
    for ch, name in {'\t': 'tab', '\r': 'carriage return'}.items():
        if ch in s:
            raise SystemExit(f'subject contains a {name}; CCE has no escape for it')
    if any(ord(c) > 127 for c in s):
        raise SystemExit('subject has non-ASCII chars; the zig runtime panics on multibyte CCE')
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


SUBJECT = codex_literal(FIB)

out = f'''Chapter: FibHarness

Section: Subject
  subject-text : Text
  subject-text = "{SUBJECT}"

Section: Driver

  show-ir-def-text : List IRDef, Integer, Integer -> [Console] Nothing
  show-ir-def-text (ds) (i) (len) = act
    if i >= len then print-line-uni "."
    else act
      print-line-uni (ir-emit-def (list-at ds i))
      show-ir-def-text ds (i + 1) len
    end
  end

  opening : [Console] Nothing = act
    let toks = tokenize subject-text 1
    in let doc = parse-document (make-parse-state (toks.tokens) subject-text) 0
    in let dr = desugar-document subject-text doc (doc.chapter-title) 0
    in let ch0 = dr.dr-chapter
    in let ch = scope-achapter ch0 skip-list-text-empty [] 0
    in let rr = resolve-chapter ch skip-list-text-empty [] 0
    in let cr = check-chapter ch [] skip-list-text-empty [] 0
    in let cst = cr.state
    in let sorted = sort-bindings (cr.types)
    in let ir = lower-chapter ch sorted cst (rr.ctor-names) [] skip-list-text-empty [] 0
    in act
      print-line-uni ("lex-tokens " & show (list-length (toks.tokens)))
      print-line-uni ("lex-errors " & show (list-length (toks.errors)))
      print-line-uni ("parse-errors " & show ((doc.parse-bag).error-count))
      print-line-uni ("resolve-errors " & show ((rr.bag).error-count))
      print-line-uni ("check-errors " & show ((cst.bag).error-count))
      print-line-uni ("ir-defs " & show (list-length (ir.defs)))
      print-line-uni "--- ir-text ---"
      show-ir-def-text (ir.defs) 0 (list-length (ir.defs))
    end
  end
'''

dest = HERE / 'FibHarness.codex'
dest.write_text(out)
print(f'{dest}: {len(out)} bytes')
